# Site Settings
locale: "en-US"
title: "Gandhimathi Padmanaban"
subtitle: ""
name: "Gandhimathi Padmanaban"
description: "Ph.D. Candidate in Industrial & Systems Engineering specializing in data-driven+physics-informed machine learning, geometry-informed computer vision, and transportation safety research."
url: "https://mathipadmanaban.github.io"
repository: "mathipadmanaban/mathipadmanaban.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

include:
  - _pages

sass:
  sass_dir: assets/css
  style: compressed

# Site Author
author:
  name: "Gandhimathi Padmanaban"
  avatar: "/assets/images/mathi-profile.jpg"
  bio: "Hybrid AI · Computer Vision · Transportation Safety"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:gmathi@umich.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mathipadmanaban67/"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Gandhimathi-Padmanaban"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5143-8948"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=aNWRkHIAAAAJ"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mathipadmanaban"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
